### ISSUE TITLE
Disruptive habitat filtering to add in man files.

### ISSUE THREAD

**Issue by pierredenelle** [adrientaudiere/lottery#5]
# Disruptive habitat filtering around t = 0.5
J <- 100
m <- 0.5
theta <- 50
comm <- coalesc(J, theta, m, filt = function(x) abs(0.5 - x))
hist(comm[, 3])

**Comment by Rekyt** [comment]
Closed by a1431009c2c5dccc0bc03f96d23f8a21072fa198
